export const storyRankings: string[] = [
  "apple.txt",
  "deshaw.txt",
  "chasebank.txt",
  "UVA.txt",
  "JavaSoft.txt",
  "asic1.txt",
  "asic2.txt",
  "best_day.txt",
  "cisco_ios.txt",
  "compuserve.txt",
  "cyber currency 101.txt",
  "electrofiberoptic.txt",
  "fastterm.txt",
  "genasm.txt",
  "genlib.txt",
  "genlink.txt",
  "genmake.txt",
  "genref.txt",
  "hewlettpackard.txt",
  "home construction.txt",
  "laser-printer.txt",
  "magnifi.txt",
  "miracleofvirginia.txt",
  "Myarc.txt",
  "national merit.txt",
  "netflix_prize.txt",
  "PaperRoute.txt",
  "resultsbyjq.txt",
  "rpi.txt",
];
